services:
  postgres:
    image: postgres:18
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: psasf2004
      POSTGRES_DB: listUsers
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql
  
  frontend:
    build: 
      context: ./frontend/listUsers
      dockerfile: Dockerfile
      args:
        VITE_API_URL: http://localhost:3000
    ports:
      - "5137:80"

  backend:
    build: 
      context: ./backend
      dockerfile: Dockerfile
    environment:
      DATABASE_URL: postgresql://postgres:psasf2004@postgres:5432/listUsers?schema=public
      JWT_SECRET: token_secret
    ports:
      - 3000:3000

volumes:
  postgres_data:
